"""empty message

Revision ID: 057de732b73d
Revises: d38a672ac3f3
Create Date: 2020-08-04 14:47:03.376632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057de732b73d'
down_revision = 'd38a672ac3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_uploads', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_uploads', 'is_approved')
    # ### end Alembic commands ###
